/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_egret0_eastl_android_NativeUtils */

#ifndef _Included_com_example_egret0_eastl_android_NativeUtils
#define _Included_com_example_egret0_eastl_android_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_egret0_eastl_android_NativeUtils
 * Method:    testEASTL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_egret0_eastl_1android_NativeUtils_testEASTL
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
